```yaml
name: CI - Tests and PHPStan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests-and-phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.4']

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up PHP with required version and extensions
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, pdo_mysql
          coverage: xdebug
          tools: composer:v2, phpstan

      # Install dependencies
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Run PestPHP tests with coverage
      - name: Run PestPHP tests
        run: vendor/bin/pest --coverage-clover clover.xml
        env:
          SESSION_DRIVER: array

      # Generate test coverage badge
      - name: Generate coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          coverage_badge_path: badge-coverage.svg
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      # Run PHPStan analysis
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=2G
```
