name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up PHP 8.4 with required extensions
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, pdo_sqlite
          coverage: xdebug
          tools: composer:v2, phpstan

      # Cache Composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      # Install Composer dependencies
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Copy .env.example to .env if it exists
      - name: Copy .env
        run: |
          if [ -f ".env.example" ]; then
            cp .env.example .env
          else
            echo "Warning: .env.example not found, skipping .env creation"
          fi

      # Generate Laravel application key
      - name: Generate key
        run: php artisan key:generate

      # Set directory permissions
      - name: Directory Permissions
        run: chmod -R 775 storage bootstrap/cache

      # Run PestPHP tests with coverage
      - name: Execute tests (Unit and Feature tests) via Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
          SESSION_DRIVER: array
        run: vendor/bin/pest --coverage-clover clover.xml

      # Generate coverage badge
      - name: Generate coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          coverage_badge_path: badge-coverage.svg
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      # Run PHPStan analysis
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=2G
